import { LeaderboardTeam, LiveMatchData, RegisteredSquad, TournamentMap } from '@/types/tournament';

export const DEFAULT_LEADERBOARD: LeaderboardTeam[] = [
  {
    id: 'team-1',
    rank: 1,
    name: 'GHOST REAPERS',
    group: 'Group A',
    played: 5,
    wins: 5,
    losses: 0,
    roundsWon: 65,
    roundsLost: 20,
    points: 15,
    status: 'CHAMPIONS',
  },
  {
    id: 'team-2',
    rank: 2,
    name: 'TITAN STRIKERS',
    group: 'Group A',
    played: 5,
    wins: 4,
    losses: 1,
    roundsWon: 58,
    roundsLost: 31,
    points: 12,
    status: 'QUALIFIED',
  },
  {
    id: 'team-3',
    rank: 3,
    name: 'VIPER TACTICAL',
    group: 'Group B',
    played: 5,
    wins: 4,
    losses: 1,
    roundsWon: 54,
    roundsLost: 35,
    points: 12,
    status: 'QUALIFIED',
  },
  {
    id: 'team-4',
    rank: 4,
    name: 'SHADOW SQUAD',
    group: 'Group B',
    played: 5,
    wins: 3,
    losses: 2,
    roundsWon: 48,
    roundsLost: 40,
    points: 9,
    status: 'CONTENDER',
  },
  {
    id: 'team-5',
    rank: 5,
    name: 'ALPHA PROTOCOL',
    group: 'Group A',
    played: 5,
    wins: 2,
    losses: 3,
    roundsWon: 39,
    roundsLost: 49,
    points: 6,
    status: 'CONTENDER',
  },
  {
    id: 'team-6',
    rank: 6,
    name: 'BRAVO SPECTRES',
    group: 'Group B',
    played: 5,
    wins: 1,
    losses: 4,
    roundsWon: 28,
    roundsLost: 56,
    points: 3,
    status: 'ELIMINATED',
  },
];

export const DEFAULT_LIVE_MATCH: LiveMatchData = {
  isLive: true,
  stageTitle: 'GRAND FINALS // BEST OF 3',
  mapName: 'mp_crash',
  roundInfo: 'ROUND 14 / 24 (HALF-TIME)',
  team1: {
    name: 'GHOST REAPERS',
    score: 8,
    side: 'ATTACKERS',
    players: ['Spectre (Sniper)', 'Wraith (Assault)', 'Shade (Assault)', 'Ember (SMG)', 'Onyx (Demo)'],
  },
  team2: {
    name: 'TITAN STRIKERS',
    score: 6,
    side: 'DEFENDERS',
    players: ['Vortex (Sniper)', 'Blitz (Assault)', 'Nova (Assault)', 'Pulse (SMG)', 'Rift (Demo)'],
  },
};

export const DEFAULT_SQUADS: RegisteredSquad[] = [
  {
    id: 'squad-1',
    teamName: 'GHOST REAPERS',
    captainName: 'Spectre',
    contactNo: '+94 77 123 4567',
    campus: 'CST Degree Program',
    members: ['Spectre (Captain)', 'Wraith (Sniper)', 'Shade (Assault)', 'Ember (SMG)', 'Onyx (Demo)'],
    status: 'VERIFIED',
    dateRegistered: '2026-09-18',
  },
  {
    id: 'squad-2',
    teamName: 'TITAN STRIKERS',
    captainName: 'Vortex',
    contactNo: '+94 71 987 6543',
    campus: 'Computer Science Faculty',
    members: ['Vortex (Captain)', 'Blitz (Sniper)', 'Nova (Assault)', 'Pulse (SMG)', 'Rift (Demo)'],
    status: 'VERIFIED',
    dateRegistered: '2026-09-19',
  },
];

export const TOURNAMENT_MAPS: TournamentMap[] = [
  {
    id: 'mp_crash',
    name: 'mp_crash',
    displayName: 'Crash',
    title: 'CRASH SITE COMBAT',
    desc: 'Downed helicopter courtyard. Fast-paced 5v5 S&D engagements.',
    tag: '5v5 SEARCH & DESTROY',
    src: '/models/images001.webp',
  },
  {
    id: 'mp_crossfire',
    name: 'mp_crossfire',
    displayName: 'Crossfire',
    title: 'CROSSFIRE OVERWATCH',
    desc: 'Central avenue sniper alley requiring tactical smoke & team coordination.',
    tag: 'SNIPER & HELI ASSAULT',
    src: '/models/image002.webp',
  },
  {
    id: 'mp_backlot',
    name: 'mp_backlot',
    displayName: 'Backlot',
    title: 'BACKLOT URBAN WARFARE',
    desc: 'Urban construction zone with multi-story sniper angles & tight choke points.',
    tag: 'CLOSE-QUARTERS TACTICAL',
    src: '/models/images003.webp',
  },
  {
    id: 'mp_strike',
    name: 'mp_strike',
    displayName: 'Strike',
    title: 'STRIKE TOWN MARKET',
    desc: 'Classic competitive map featuring balanced bomb sites A & B.',
    tag: 'TACTICAL BOMB DEFUSAL',
  },
  {
    id: 'mp_citystreets',
    name: 'mp_citystreets',
    displayName: 'District',
    title: 'DISTRICT NIGHT COMBAT',
    desc: 'Nighttime tactical warfare with flanking routes & close-quarters combat.',
    tag: 'URBAN FLANK ASSAULT',
  },
];

export const DEFAULT_ROSTERS: Record<string, string[]> = {
  'GHOST REAPERS': ['Spectre (Captain)', 'Wraith (Sniper)', 'Shade (Assault)', 'Ember (SMG)', 'Onyx (Demo)'],
  'TITAN STRIKERS': ['Vortex (Captain)', 'Blitz (Sniper)', 'Nova (Assault)', 'Pulse (SMG)', 'Rift (Demo)'],
  'VIPER TACTICAL': ['Viper (Captain)', 'Venom (Sniper)', 'Cobra (Assault)', 'Fang (SMG)', 'Toxin (Demo)'],
  'SHADOW SQUAD': ['Shadow (Captain)', 'Ghost (Sniper)', 'Phantom (Assault)', 'Mirage (SMG)', 'Spectre (Demo)'],
  'ALPHA PROTOCOL': ['Alpha (Captain)', 'Ares (Sniper)', 'Titan (Assault)', 'Zeus (SMG)', 'Hades (Demo)'],
  'BRAVO SPECTRES': ['Bravo (Captain)', 'Echo (Sniper)', 'Foxtrot (Assault)', 'Sierra (SMG)', 'Tango (Demo)'],
};
