import { LeaderboardTeam, LiveMatchData, RegisteredSquad } from '@/types/tournament';

export const DEFAULT_LEADERBOARD: LeaderboardTeam[] = [
  {
    id: 'team-1',
    rank: 1,
    name: 'GHOST REAPERS',
    group: 'Group A',
    played: 5,
    wins: 5,
    losses: 0,
    roundsWon: 65,
    roundsLost: 20,
    points: 15,
    status: 'CHAMPIONS',
  },
  {
    id: 'team-2',
    rank: 2,
    name: 'TITAN STRIKERS',
    group: 'Group A',
    played: 5,
    wins: 4,
    losses: 1,
    roundsWon: 58,
    roundsLost: 31,
    points: 12,
    status: 'QUALIFIED',
  },
  {
    id: 'team-3',
    rank: 3,
    name: 'VIPER TACTICAL',
    group: 'Group B',
    played: 5,
    wins: 4,
    losses: 1,
    roundsWon: 54,
    roundsLost: 35,
    points: 12,
    status: 'QUALIFIED',
  },
  {
    id: 'team-4',
    rank: 4,
    name: 'SHADOW SQUAD',
    group: 'Group B',
    played: 5,
    wins: 3,
    losses: 2,
    roundsWon: 48,
    roundsLost: 40,
    points: 9,
    status: 'CONTENDER',
  },
  {
    id: 'team-5',
    rank: 5,
    name: 'ALPHA PROTOCOL',
    group: 'Group A',
    played: 5,
    wins: 2,
    losses: 3,
    roundsWon: 39,
    roundsLost: 49,
    points: 6,
    status: 'CONTENDER',
  },
  {
    id: 'team-6',
    rank: 6,
    name: 'BRAVO SPECTRES',
    group: 'Group B',
    played: 5,
    wins: 1,
    losses: 4,
    roundsWon: 28,
    roundsLost: 56,
    points: 3,
    status: 'ELIMINATED',
  },
];

export const DEFAULT_LIVE_MATCH: LiveMatchData = {
  isLive: true,
  stageTitle: 'GRAND FINALS // BEST OF 3',
  mapName: 'mp_crash',
  roundInfo: 'ROUND 14 / 24 (HALF-TIME)',
  team1: {
    name: 'GHOST REAPERS',
    score: 8,
    side: 'ATTACKERS',
    players: ['Kasun (Sniper)', 'Nimal (Assault)', 'Sunil (Assault)', 'Kamal (SMG)', 'Ruwan (Demo)'],
  },
  team2: {
    name: 'TITAN STRIKERS',
    score: 6,
    side: 'DEFENDERS',
    players: ['Dinesh (Sniper)', 'Pathum (Assault)', 'Amila (Assault)', 'Sahan (SMG)', 'Janith (Demo)'],
  },
};

export const DEFAULT_SQUADS: RegisteredSquad[] = [
  {
    id: 'squad-1',
    teamName: 'GHOST REAPERS',
    captainName: 'Kasun Perera',
    contactNo: '+94 77 123 4567',
    campus: 'CST Degree Program',
    members: ['Kasun (Captain)', 'Nimal (Sniper)', 'Sunil (Assault)', 'Kamal (SMG)', 'Ruwan (Demo)'],
    status: 'VERIFIED',
    dateRegistered: '2026-09-18',
  },
  {
    id: 'squad-2',
    teamName: 'TITAN STRIKERS',
    captainName: 'Dinesh Fernando',
    contactNo: '+94 71 987 6543',
    campus: 'Computer Science Faculty',
    members: ['Dinesh (Captain)', 'Pathum (Sniper)', 'Amila (Assault)', 'Sahan (SMG)', 'Janith (Demo)'],
    status: 'VERIFIED',
    dateRegistered: '2026-09-19',
  },
];
